### ISSUE TITLE
WordNetAug - index error

### ISSUE THREAD

**Issue by jessicasousa** [makcedward/nlpaug#10]
Hello, when I put a text that contains one character words like: 'I a' , in the wordnet synom replacement , the following bug occurs:

> text= "I work in a middle school"
> aug = naw.WordNetAug()
> augmented_text = aug.augment(text)

![image](https://user-images.githubusercontent.com/24496820/59557558-4f11df00-8fb3-11e9-8843-9a70155249a7.png)

**Comment by makcedward** [comment]
Merge [changes ](https://github.com/makcedward/nlpaug/pull/11)to resolve this problem.
