### ISSUE TITLE
Naming inconsistency of inputs to RandomCharAug and KeyboardAug

### ISSUE THREAD

**Issue by ogencoglu** [makcedward/nlpaug#111]
KeyboardAug has _upper_case_ and RandomCharAug has _include_upper_case_ and similar other stuff. Would be nice to standardize.

**Comment by ogencoglu** [comment]
_spec_char_ vs. _special_char_ etc.

**Comment by makcedward** [comment]
Yes, parameters should be standardized. Will work on it.
