### ISSUE TITLE
UnicodeDecodeError on bert model

### ISSUE THREAD

**Issue by Vonisoa** [makcedward/nlpaug#113]
Hi, I tested the bert-base-uncased model but I have downloaded this before.
So the augmenter instantiation is like this:
`aug = naw.ContextualWordEmbsAug(model_path='bert-base-uncased-pytorch_model.bin', action="substitute")`

But when I run the code, I got the following error:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by grayskripko** [comment]
what if you remove `-pytorch_model.bin`?
I guess you pass an unallowed model

**Comment by makcedward** [comment]
It seems like transfomers library changed model format. Suggest to download the latest model and installing the latest transformers version
