### ISSUE TITLE
ModuleNotFoundError : No module named 'nlpaug.augmenter'; 'nlpaug' is not a package

### ISSUE THREAD

**Issue by gulkaur** [makcedward/nlpaug#120]
I followed below steps :
pip install nlpaug numpy matplotlib python-dotenv

Import nlpaug

Getting below error -
ModuleNotFoundError : No module named 'nlpaug.augmenter'; 'nlpaug' is not a package

**Comment by ankurgulati** [comment]
I am facing the same issue

**Comment by makcedward** [comment]
What version are you installed? You may get the version number by executing the following code
```
import nlpaug
nlpaug.__version__
```

On the other hand, you may try to uninstall the package and reinstall it without cache

`pip --no-cache-dir install nlpaug`

**Comment by fkurushin** [comment]
> What version are you installed? You may get the version number by executing the following code
> 
> ```
> import nlpaug
> nlpaug.__version__
> ```
> 
> On the other hand, you may try to uninstall the package and reinstall it without cache
> 
> `pip --no-cache-dir install nlpaug`

im sorry, I don't understand, how can I import nlpaug, to check the version, if I have error with importing?

**Comment by virilo** [comment]
@gulkaur   Just avoid naming your script "nlpaug.py", as I did.  Renaming the script solved the issue for me
