### ISSUE TITLE
Sometimes not working with contextual embeddings

### ISSUE THREAD

**Issue by rxjx** [makcedward/nlpaug#122]
INPUT:
bert_insert = naw.ContextualWordEmbsAug(model_path='bert-large-uncased-whole-word-masking',action='insert')
bert_sub = naw.ContextualWordEmbsAug(model_path='bert-large-uncased-whole-word-masking',action='substitute')
RoBERTa_sub= naw.ContextualWordEmbsAug(model_path = 'roberta-large',action='substitute')
XLNet_sub= naw.ContextualWordEmbsAug(model_path = 'xlnet-large-cased',action='substitute')
aug = naf.Sometimes(bert_sub, RoBERTa_sub, XLNet_sub)

aug.augment('This is a test')

OUTPUT:
/usr/local/lib/python3.6/dist-packages/nlpaug/flow/sometimes.py in draw(self)
     28 
     29     def draw(self):
---> 30         return self.pipeline_p > self.prob()

TypeError: '>' not supported between instances of 'ContextualWordEmbsAug' and 'float'

**Comment by makcedward** [comment]
Hi @rxjx 

You need to provide a list of augmenter. 

Here is the example
`aug = naf.Sometimes([bert_sub, RoBERTa_sub, XLNet_sub])`
