### ISSUE TITLE
Support for other languages?

### ISSUE THREAD

**Issue by mzeidhassan** [makcedward/nlpaug#124]
Hi there,
First, thanks for creating such a great library. It's super useful. Do you plan to support other languages? I tried to use RandomCharAug with Arabic text, but unfortunately it keeps using English characters instead.

If I want to change that, can you please indicate which files need to be modified?

Is there an easy way to support languages other than English?

Thanks,
Mohamed

**Comment by makcedward** [comment]
Will enhance it to provide params for that.

**Comment by makcedward** [comment]
Enhanced

**Comment by mzeidhassan** [comment]
> Enhanced

Sorry @makcedward for reopening the issue, but does this mean that it's already enhanced? If yes, can you please guide me to where to support Arabic for example? What params to use now? 

Thanks in advance for your support!

**Comment by makcedward** [comment]
As I am not familiar with other languages, I cannot predefine a list of characters. Therefore, I decide to allow a user to provide inputs such that augmenter picks the provided candidates list and applying augmentation. 

You may try the following sample code

```
candidiates = ['AAA', '11', '===']
text = 'quick brown jumps over lazy'
aug = RandomCharAug(candidiates=candidiates)
augmented_text = aug.augment(text)
```
