### ISSUE TITLE
Unable to load augmenter.word

### ISSUE THREAD

**Issue by Luedag** [makcedward/nlpaug#128]
Hey there!

I was trying to do some word-based augmentation but couldn't get past the imports. When I try to access nlpaug.augmenter.word it gives me an error saying:

AttributeError: module 'nlpaug.augmenter' has no attribute 'word'

In fact, it doesn't let me load anything within nlpaug.augmenter

Your help would be much appreciated! Thanks.

**Comment by makcedward** [comment]
You may need to uninstall it and re-installing without cache.

`pip install --upgrade --force-reinstall nlpaug`
