### ISSUE TITLE
typo fix of doc of "nlpaug.augmenter.audio.crop"

### ISSUE THREAD

**Issue by Owen864720655** [makcedward/nlpaug#134]
It seems that the illustration of the parameter **coverage** is not correct.

## Old
For example, the audio duration is 60 seconds while zone and coverage are (0.2, 0.8) and 0.7 respectively. **42** seconds ((0.8-0.2)*0.7*60) audio will be augmented.

## New
For example, the audio duration is 60 seconds while zone and coverage are (0.2, 0.8) and 0.7 respectively. **25.2** seconds ((0.8-0.2)*0.7*60) audio will be augmented.

**Comment by makcedward** [comment]
Will correct it in next release.
