### ISSUE TITLE
Google W2Vec bin is not found

### ISSUE THREAD

**Issue by MurliJadhav** [makcedward/nlpaug#135]
GoogleNews-vectors-negative300 is not unzipping succefully. 

I am running this https://github.com/makcedward/nlpaug/blob/master/example/textual_augmenter.ipynb

So that it is not able to find the bin file

**Comment by makcedward** [comment]
You need to download the file first. You may download it from this web site 
https://github.com/mmihaltz/word2vec-GoogleNews-vectors

**Comment by MurliJadhav** [comment]
HI The actual issue is different see this error
ValueError                                Traceback (most recent call last)
<ipython-input-46-f8c24745cfe5> in <module>()
      1 aug = naw.WordEmbsAug(
      2     model_type='word2vec', model_path='/content/glove.6B.300d.txt',
----> 3     action="insert")
      4 augmented_text = aug.augment("mu")
      5 print("Original:")

3 frames
/usr/local/lib/python3.6/dist-packages/nlpaug/model/word_embs/word2vec.py in read(self, file_path, max_num_vector)
     12         with open(file_path, 'rb') as f:
     13 
---> 14             header = f.readline()
     15 
     16             self.vocab_size, self.emb_size = map(int, header.split())

ValueError: invalid literal for int() with base 10: b'the'

I already have all files. also it always giving the invalid literal for word2vec.py file
please update word2vec.py file or give me solution for now :)

**Comment by MurliJadhav** [comment]
Hi the error is in Word2Vec file for the GoogleNewsWord2Vec file

ValueError                                Traceback (most recent call last)
<ipython-input-55-b76e47cab611> in <module>()
      1 aug = naw.WordEmbsAug(
      2     model_type='word2vec', model_path='/content/GoogleNews-vectors-negative300.bin.gz',
----> 3     action="insert")
      4 augmented_text = aug.augment(text)
      5 print("Original:")

3 frames
/usr/local/lib/python3.6/dist-packages/nlpaug/model/word_embs/word2vec.py in read(self, file_path, max_num_vector)
     12         with open(file_path, 'rb') as f:
     13 
---> 14             header = f.readline()
     15 
     16             self.vocab_size, self.emb_size = map(int, header.split())

ValueError: invalid literal for int() with base 10: b'\x1f\x8b\x08\x08\x80\xff\xa8R\x02\x03GoogleNews-vectors-negative300.bin\x00L\x9d\x07\xbc\xce\xf5\xfb\xff\xad\x902#\xbb\x8cP\x19\x99\xc5\xb9\xefsTF\xd1\x92R\xd1DB\x11E\xa9\xbe'

See above error. If possible please correct the word2vec file or please give the soltion . it would be very helpfull :)

**Comment by makcedward** [comment]
Noticed your file is GoogleNews-vectors-negative300.bin**.gz** You need to provide an unzipped binary file. Please again with non-compressed file.

**Comment by witzatom** [comment]
you can download the model with
```
from nlpaug.util.file.download import DownloadUtil
DownloadUtil.download_word2vec(dest_dir=model_dir)
```
The downloader incorrectly saves the model with a .zip extension, even though it is a gzip file. You can gunzip it with `gunzip -c -S zip ./model/GoogleNews-vectors-negative300.zip > ./model/GoogleNews-vectors-negative300.bin`.
