### ISSUE TITLE
Stopwords

### ISSUE THREAD

**Issue by abcp4** [makcedward/nlpaug#14]
Hello, it seems like the stopwords aren't being filtered correctly:

![image](https://user-images.githubusercontent.com/8815320/61661268-0af4b700-aca2-11e9-9703-a2fd3627e484.png)

The 'quick' word is not being ignored. It would be nice if it would just pass over them

**Comment by abcp4** [comment]
A new issue with stopwords: 
![image](https://user-images.githubusercontent.com/8815320/61910610-860cd600-af0b-11e9-95a7-a03480183dc2.png)

![image](https://user-images.githubusercontent.com/8815320/61910635-91600180-af0b-11e9-9a9c-52ae7dc2375c.png)

![image](https://user-images.githubusercontent.com/8815320/61910655-9a50d300-af0b-11e9-9637-3930e628b2ad.png)
It seems like punctuation is turning it in a new word. Like, dog is not being filtered because of 'dog.' is being seen as a word.

**Comment by makcedward** [comment]
You are right. Default tokenizer is splitting word by space.
`tokens = text.split(' ')`

Will enhance the implementation of tokenizer. Before that, there are 2 ways to overcome it.
1. Split punctuation. For example, changing input to 'The quick brown fox , jumps over the lazy dog .'.
2. Override custom tokenzier to the augmenter. 
```
import re
# The _tokenizer is not good enough as punctuation will be removed in return.
def _tokenizer(text, token_pattern=r"(?u)\b\w\w+\b"):
            token_pattern = re.compile(token_pattern)
            return token_pattern.findall(text)

aug = nac.QwertyAug()
aug.tokenizer = _tokenizer
```
