### ISSUE TITLE
Load back translation models from local path

### ISSUE THREAD

**Issue by Samarthagarwal23** [makcedward/nlpaug#149]
By default, it tries to download from torch hub.
Can you enable functionality to load model from local path?

**Comment by makcedward** [comment]
Enhanced in version 1.0.0. Will be released by end of this month. Before that you can try to pull from github for earlier access.

You need to set new parameter (i.e. is_load_from_github) to False. The following is a sample code or you can go to this [notebook ](https://github.com/makcedward/nlpaug/blob/master/example/textual_augmenter.ipynb) for reference.
```
# Load models from local path
import nlpaug.augmenter.word as naw

from_model_dir = os.path.join(os.environ["MODEL_DIR"], 'word', 'fairseq', 'wmt19.en-de')
to_model_dir = os.path.join(os.environ["MODEL_DIR"], 'word', 'fairseq', 'wmt19.de-en')

text = 'The quick brown fox jumped over the lazy dog'
back_translation_aug = naw.BackTranslationAug(
    from_model_name=from_model_dir, from_model_checkpt='model1.pt',
    to_model_name=to_model_dir, to_model_checkpt='model1.pt', 
    is_load_from_github=False)
back_translation_aug.augment(text)

```

**Comment by makcedward** [comment]
Fixed in 1.0.0 version

**Comment by Enriquesec** [comment]
Hi, I'm trying to load a model from a local path (using version 1.1.10), but I'm getting an error.

![image](https://user-images.githubusercontent.com/42711476/160295671-ca72f38e-54b7-4568-8bd2-954d23da7e6c.png)

Does the example above (or in the example notebook) only work for version 1.0.0? Or How can I reload translation models from a local path?

Thanks

**Comment by Meywether** [comment]
'+' 1 
 Same error, on Windows.

**Comment by makcedward** [comment]
You may access this [notebook ](https://github.com/makcedward/nlpaug/blob/master/example/textual_augmenter.ipynb)for examples or you can try the following code. 

```
import nlpaug.augmenter.word as naw

text = 'The quick brown fox jumped over the lazy dog'
back_translation_aug = naw.BackTranslationAug(
    from_model_name='facebook/wmt19-en-de', 
    to_model_name='facebook/wmt19-de-en'
)
back_translation_aug.augment(text)
```
