### ISSUE TITLE
working with CPU

### ISSUE THREAD

**Issue by saeedEnte** [makcedward/nlpaug#150]
Seems that the augmenters do not work with CPU. I have changed the file "context_word_embs.py" a bit. So I transfer the data in to self.device and not necessarily cuda.

**Comment by makcedward** [comment]
Would you mind sharing what is the exception? 

If passing None/ "cpu" for device parameter, it should use CPU for processing.

**Comment by saeedEnte** [comment]
by default "cuda" will be used (based on the default parameters of the method `get_model`). It was about installing the NVIDIA drives correctly and making sure that you have gpu on your device.
