### ISSUE TITLE
ModuleNotFoundError: No module named 'nlpaug.model.spectrogram.loudness'

### ISSUE THREAD

**Issue by Charlie0215** [makcedward/nlpaug#156]
error happened while running I followed below steps :
pip install nlpaug

import nlpaug.augmenter.spectrogram as nas

Getting below error -
from nlpaug.model.spectrogram.loudness import *
ModuleNotFoundError: No module named 'nlpaug.model.spectrogram.loudness'

**Comment by makcedward** [comment]
the file is missing. will supplement it soon
