### ISSUE TITLE
Mistake in the documentation?

### ISSUE THREAD

**Issue by SpamBiereSki** [makcedward/nlpaug#158]
Hi, 

Your work is impressing, thanks a lot!

I only have a question: in the SpeedAug documentation, for the audio, it is mentioned that the parameter factor is an `int`.

However:
* The default value is not an `int`;
* Instantiating the augmenter works, but then the function `get_random_factor` is called and requires that the factor is a tuple (I think..?), and an error is raised.

I don't know if I have the wrong version, but I only wanted to mention it because I think this library is perfect otherwise.

Thanks a lot, again.

**Comment by makcedward** [comment]
The data type in the previous version is INT but it changed to tuple. Will update the documentation. Thank you very much,
