### ISSUE TITLE
Integer division error due to version

### ISSUE THREAD

**Issue by shaoxia57** [makcedward/nlpaug#159]
Hi, I'm trying to run the back translation augmentation code in the example notebook:

`import nlpaug.augmenter.word as naw`

`text = 'The quick brown fox jumped over the lazy dog'`
`back_translation_aug = naw.BackTranslationAug(`
    `from_model_name='transformer.wmt19.en-de',`
    `to_model_name='transformer.wmt19.de-en')`
`back_translation_aug.augment(text)`

but got the following error:

> RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

I'm running on python 3.6.0, pytorch 1.6.0, fairseq 0.9.0, and nlpaug 1.0.1. Should I install another version of any of the packages?

Thanks in advance!

**Comment by makcedward** [comment]
Tried several python version. Noticed that python 3.6 version will hit this exception while 3.7 and 3.8 are ok. May consider upgrading python to 3.7 or 3.8 version.

**Comment by shaoxia57** [comment]
Thanks for your response. I installed python 3.7.9 and still got the same error. 
Here is the last traceback:
`~/.conda/envs/RICA/lib/python3.7/site-packages/fairseq/search.py in step(self, step, lprobs, scores)`
    ` 79             out=(self.scores_buf, self.indices_buf),`
   `  80         )`
`---> 81         torch.div(self.indices_buf, vocab_size, out=self.beams_buf)`
    ` 82         self.indices_buf.fmod_(vocab_size)`
   `  83         return self.scores_buf, self.indices_buf, self.beams_buf`

`RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.`

**Comment by makcedward** [comment]
Just check out from fairseq repo (https://github.com/pytorch/fairseq/issues/2544#issuecomment-695812137), it is fixed in fairseq master brach. However, the fix does not release officially (published to pip). You may try the following code to upgrade fairseq to latest one.

```
git clone https://github.com/pytorch/fairseq/
cd fairseq
pip install -e .
```
