### ISSUE TITLE
unbale to use Xlnet model for augment !

### ISSUE THREAD

**Issue by Elfilali-Taoufiq** [makcedward/nlpaug#164]
i'm tryong to use model_path: xlnet-base-cased  for ContextualWordEmbsForSentenceAug:

aug = nas.ContextualWordEmbsForSentenceAug(model_path='xlnet-base-cased')

But i get the error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-7b83ee16f4aa> in <module>()
      1 # model_path: xlnet-base-cased or gpt2
----> 2 aug = nas.ContextualWordEmbsForSentenceAug(model_path='xlnet-base-cased')
      3 augmented_texts = aug.augment(text, n=3)
      4 print("Original:")
      5 print(text)

3 frames
/usr/local/lib/python3.6/dist-packages/nlpaug/model/lang_models/xlnet.py in __init__(self, model_path, temperature, top_k, top_p, padding_text, optimize, device, silence)
     44         # TODO: Evaluted to use mems in XLNet but the result is quite weird.
     45         self.optimize['external_memory'] = 0
---> 46         self.tokenizer = AutoTokenizer.from_pretrained(model_path)
     47         self.mask_id = self.token2id(self.MASK_TOKEN)
     48         self.pad_id = self.token2id(self.PAD_TOKEN)

NameError: name 'AutoTokenizer' is not defined

**Comment by makcedward** [comment]
What are versions of python, pytorch, transfomers and nlpaug?

**Comment by Elfilali-Taoufiq** [comment]
hello  @makcedward , thanks for responding,

Python 3.6.9
torch : 1.6.0+cu101
transformers : 3.3.1
nlpuag :  nlpaug-1.0.1

**Comment by makcedward** [comment]
Tried to simulate the environment. I did not meet this exception. Can you try to execute the following codes? 

`from transformers import AutoTokenizer`

**Comment by makcedward** [comment]
I cannot reproduce this issue. I changed library import statements, see if it helped. Does not push pip yet, only available on master branch.

**Comment by makcedward** [comment]
Using Colab? https://github.com/makcedward/nlpaug/issues/161#issuecomment-716035788
