### ISSUE TITLE
Bugfix for issue #203539

### ISSUE THREAD

**Issue by dugu9sword** [makcedward/nlpaug#166]
I think there is a bug in the char augmenter:

https://github.com/makcedward/nlpaug/blob/5238e0be734841b69651d2043df535d78a8cc594/nlpaug/augmenter/char/char_augmenter.py#L98

the behavior is not consistent with that of the word augmenter:

https://github.com/makcedward/nlpaug/blob/5238e0be734841b69651d2043df535d78a8cc594/nlpaug/augmenter/word/word_augmenter.py#L80

this is related to issue #203539

After changing `return None` to `return []`, the code below will not raise an exception.

```
import nlpaug.augmenter.char as nac
aug = nac.KeyboardAug(aug_word_min=0.0, aug_word_p=0.05)
aug.augment("| 4 ||  || ½ || 0 || ½ || - || 1 || 1 || 1 || 0 || 0 || 0 || 1 || 1 || 1 || 1 || 1 || 1 || 10 || 67.75")
```

**Comment by makcedward** [comment]
May you share the link for #203539 ?

**Comment by dugu9sword** [comment]
Sorry for my mistake, it should be issue #114

**Comment by makcedward** [comment]
Thanks for pointing out the bug. Fixed.
