### ISSUE TITLE
"\u2022", "\u2026", and other sub-strings appear in the augmented sentences

### ISSUE THREAD

**Issue by saeedEnte** [makcedward/nlpaug#174]
Hi,

when I try to augment the sentences of my dataset (using word augmentation with contextual language model), after a few tries, these sub-strings start to appear in the augmented sentences. It seems that these are ascii code of special symbols like bullet-point. Do you have any idea why this happens?

**Comment by makcedward** [comment]
may you share a sample inputs?

**Comment by saeedEnte** [comment]
> may you share a sample inputs?


Hi @makcedward and thank you for your support. Here is the code that I use in my application:
`aug = naw.ContextualWordEmbsAug(model_path='distilbert-base-uncased', action="insert", aug_p=0.3, top_k=100, top_p=None)`
`generated_sents.append(aug.augment(input_sent, n=1))`

Please note that the `input_sent` doesn't have any sentence with such unicodes.

**Comment by makcedward** [comment]
did you include "•" or "…" in your input?

**Comment by saeedEnte** [comment]
No, the dataset that I have, doesn't have any character with such unicodes. "{" is also the case for some tries. For apostrophe, the dataset has this kind of notion which seems a bit suspicious to me "\\'s". Could it be the reason why the network produces such characters?

**Comment by makcedward** [comment]
Yes, the network is able to produce this kind of character. I suspect your system able to decode unicode? because \u2022 is • and \u2026 is … respectively.

**Comment by saeedEnte** [comment]
As you said, it seems that the browser which shows the results in a json format, is incapable of encoding it. We have tried it on other machines and this is still the case. Running the code in the debug mode, results in the characters to be displayed in the console exactly the way that you said. I decided to filter out the characters with these unicodes. Thanks.
