### ISSUE TITLE
nas.ContextualWordEmbsForSentenceAug failing with TypeError: forward() got an unexpected keyword argument 'past'

### ISSUE THREAD

**Issue by amitkml** [makcedward/nlpaug#182]
Hi,
I have tried to use nas.ContextualWordEmbsForSentenceAug in colab and it s failing with following error.

text = 'The quick brown fox jumps over the lazy dog .'
aug = nas.ContextualWordEmbsForSentenceAug(model_path='gpt2')
augmented_text = aug.augment(text)
print("Original:")
print(text)
print("Augmented Text:")
print(augmented_text)

Error Details
TypeError                                 Traceback (most recent call last)
<ipython-input-72-6cf50b1c5e70> in <module>()
      1 text = 'The quick brown fox jumps over the lazy dog .'
      2 aug = nas.ContextualWordEmbsForSentenceAug(model_path='gpt2')
----> 3 augmented_text = aug.augment(text)
      4 print("Original:")
      5 print(text)

3 frames
/usr/local/lib/python3.6/dist-packages/nlpaug/base_augmenter.py in augment(self, data, n, num_thread)
     93                 # https://discuss.pytorch.org/t/using-cuda-multiprocessing-with-single-gpu/7300
     94                 for _ in range(aug_num):
---> 95                     result = action_fx(clean_data)
     96                     if isinstance(result, list):
     97                         augmented_results.extend(result)

/usr/local/lib/python3.6/dist-packages/nlpaug/augmenter/sentence/context_word_embs_sentence.py in insert(self, data)
    144 
    145             outputs = self.model.predict(texts, n=1, external_memory=external_memory, 
--> 146                 include_punctuation=True)
    147 
    148             for i, output in enumerate(outputs):

/usr/local/lib/python3.6/dist-packages/nlpaug/model/lang_models/gpt2.py in predict(self, texts, target_words, n, external_memory, include_punctuation)
     69         results = []
     70         with torch.no_grad():
---> 71             outputs = self.model(input_ids=input_idxes, attention_mask=mask_inputs, past=external_memory)
     72 
     73         # Selection

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

TypeError: forward() got an unexpected keyword argument 'past'

**Comment by makcedward** [comment]
Able to reproduce by using transformers 4.0 version. It is fine when using 3.x version. The root cause is API changed in transformers. Will fix it
