### ISSUE TITLE
factor() in docs

### ISSUE THREAD

**Issue by fmailhot** [makcedward/nlpaug#185]
API docs for audio augmenter all say the same thing for `factor`, i.e.

`Input data volume will be increased (decreased). Augmented value will be picked within the range of this tuple value. Volume will be reduced if value is between 0 and 1.`

see e.g. https://nlpaug.readthedocs.io/en/latest/augmenter/audio/speed.html

**Comment by makcedward** [comment]
Thank you for reporting it. Will fix it in the coming release
