### ISSUE TITLE
AttributeError: 'BertTokenizerFast' object has no attribute '_convert_token_to_id'

### ISSUE THREAD

**Issue by Somabhadra** [makcedward/nlpaug#187]
my code
#BERT Augmentator
TOPK=20 #default=100
ACT = 'insert' #"substitute"

aug_bert = naw.ContextualWordEmbsAug(
    model_path='bert-base-multilingual-uncased', 
    #device='cuda',
    action=ACT, top_k=TOPK)
print("Original:")
print(text)
print("Augmented Text:")
for ii in range(5):
    augmented_text = aug_bert.augment(text)
    print(augmented_text)
please let me  know how can i fixed this issue.
transformer=4.0.1
pytorch=1.7.0+cu101
nlpaug=1.1.0

**Comment by makcedward** [comment]
[Fixed ](https://github.com/makcedward/nlpaug/commit/935e68a4faf265729340ce7984a3619d52d27f7f)in nlpaug 1.1.1. Please upgrade it and try again

**Comment by Somabhadra** [comment]
Yes fixed it..thanks a lot Mak

**Comment by sohang3112** [comment]
This issue should be re-opened - I'm again getting same error with version 1.1.11 (latest). Downgrading to version 1.1.1 (suggested above) aslo didn't help.
