### ISSUE TITLE
BertTokenizerFast object has no attribute __convert_to_id

### ISSUE THREAD

**Issue by DaryLee** [makcedward/nlpaug#188]
I get this error when i try to run `aug = naw.ContextualWordEmbsAug(model_path=path)`

i followed your install instruction and i am using bert-german-cased

`~\.conda\envs\lib\site-packages\nlpaug\model\lang_models\bert.py in __init__(self, model_path, temperature, top_k, top_p, device, silence)
     31 
     32         self.tokenizer = AutoTokenizer.from_pretrained(model_path)
---> 33         self.mask_id = self.token2id(self.MASK_TOKEN)
     34         self.pad_id = self.token2id(self.PAD_TOKEN)
     35         if silence:

~\.conda\envs\lib\site-packages\nlpaug\model\lang_models\bert.py in token2id(self, token)
     50 
     51     def token2id(self, token):
---> 52         return self.tokenizer._convert_token_to_id(token)
     53 
     54     def id2token(self, _id):

AttributeError: 'BertTokenizerFast' object has no attribute '_convert_token_to_id'`

**Comment by makcedward** [comment]
It is caused by transformer API broken from 4.x. You may upgrade nlpaug to 1.1.1 version. #187
