### ISSUE TITLE
Issue with gensim created word2vec

### ISSUE THREAD

**Issue by DaryLee** [makcedward/nlpaug#200]
So i stumbled across a new problem when creating augmented documents with word2vec.

i always land in the assertion that i2w and w2i are not similar. so i really just create a simple word2vec file with gensim out of my documents

`# model_type: word2vec, glove or fasttext
aug = naw.WordEmbsAug(
    model_type='word2vec', model_path=os.path.join(work_dir, 'ccspacy_w2v.bin'),
    action="substitute")
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-7823b5cfb15a> in <module>
      2 aug = naw.WordEmbsAug(
      3     model_type='word2vec', model_path=os.path.join(work_dir, 'ccspacy_w2v.bin'),
----> 4     action="substitute")

nlpaug\augmenter\word\word_embs.py in __init__(self, model_type, model_path, model, action, name, aug_min, aug_max, aug_p, top_k, n_gram_separator, stopwords, tokenizer, reverse_tokenizer, force_reload, stopwords_regex, verbose)
     84         if model is None:
     85             self.model = self.get_model(model_path=model_path, model_type=model_type, force_reload=force_reload,
---> 86                                         top_k=self.top_k)
     87         else:
     88             self.model = model

nlpaug\augmenter\word\word_embs.py in get_model(cls, model_path, model_type, force_reload, top_k)
     94     @classmethod
     95     def get_model(cls, model_path, model_type, force_reload=False, top_k=100):
---> 96         return init_word_embs_model(model_path, model_type, force_reload, top_k=top_k)
     97 
     98     def skip_aug(self, token_idxes, tokens):

nlpaug\augmenter\word\word_embs.py in init_word_embs_model(model_path, model_type, force_reload, top_k)
     21     if model_type == 'word2vec':
     22         model = nmw.Word2vec(top_k=top_k)
---> 23         model.read(model_path)
     24     elif model_type == 'glove':
     25         model = nmw.GloVe(top_k=top_k)

nlpaug\model\word_embs\word2vec.py in read(self, file_path, max_num_vector)
     46                 raise AssertionError('Vector Size:{}, Index2Word Size:{}'.format(len(vectors), len(self.i2w)))
     47             if len(self.i2w) != len(self.w2i):
---> 48                 raise AssertionError('Index2Word Size:{}, Word2Index Size:{}'.format(len(self.i2w), len(self.w2i)))
     49             if len(self.w2i) != len(self.w2v):
     50                 raise AssertionError('Word2Index Size:{}, Word2Vector Size:{}'.format(len(self.w2i), len(self.w2v)))

AssertionError: Index2Word Size:188381, Word2Index Size:110529`

Is this error known ?

**Comment by makcedward** [comment]
I suspected that It is caused by duplicate values.
