### ISSUE TITLE
TFIDF Augmenter Value Error

### ISSUE THREAD

**Issue by DaryLee** [makcedward/nlpaug#201]
i also tried the example TFIDF Augmenter from your examples...but the i get the following error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-51-28c4baad8507> in <module>
      1 aug = naw.TfIdfAug(model_path=os.environ.get("MODEL_DIR"),
----> 2     action="insert")

c:\users\azd2rlz\downloads\nlpaug-master\nlpaug\augmenter\word\tfidf.py in __init__(self, model_path, action, name, aug_min, aug_max, aug_p, top_k, stopwords, tokenizer, reverse_tokenizer, stopwords_regex, verbose)
     58         self.model_path = model_path
     59         self.top_k = top_k
---> 60         self.model = self.get_model(force_reload=False)
     61 
     62     def skip_aug(self, token_idxes, tokens):

c:\users\azd2rlz\downloads\nlpaug-master\nlpaug\augmenter\word\tfidf.py in get_model(self, force_reload)
    172 
    173     def get_model(self, force_reload=False):
--> 174         return init_tfidf_model(self.model_path, force_reload)

c:\users\azd2rlz\downloads\nlpaug-master\nlpaug\augmenter\word\tfidf.py in init_tfidf_model(model_path, force_reload)
     17 
     18     tfidf_model = nmws.TfIdf()
---> 19     tfidf_model.read(model_path)
     20     TFIDF_MODEL = tfidf_model
     21 

c:\users\azd2rlz\downloads\nlpaug-master\nlpaug\model\word_stats\tfidf.py in read(self, model_path)
    110         with open(os.path.join(model_path, self.WORD_2_IDF_FILE_NAME), 'r', encoding="utf-8") as f:
    111             for line in f.readlines():
--> 112                 w, s = line.split(' ')
    113                 self.w2idf[w] = float(s)
    114 

ValueError: too many values to unpack (expected 2)

**Comment by makcedward** [comment]
If the TFIDF is trained by my library, it should not throw this exception, You may try to upgrade to the latest version ( not yet release to pip yet, install it through `pip install git+https://github.com/makcedward/nlpaug.git`

Please try it and post the exception here
