### ISSUE TITLE
Not Use GPU

### ISSUE THREAD

**Issue by mustfkeskin** [makcedward/nlpaug#208]
Hello

I try bert for data augmentation
Runtime is too slow because not using gpu

I install torch with conda 
what i have missing
`conda install pytorch torchvision torchaudio cudatoolkit=10.1 -c pytorch
`
`naw.ContextualWordEmbsAug(model_path='bert-base-uncased', aug_p=0.25)`

**Comment by makcedward** [comment]
try

`naw.ContextualWordEmbsAug(model_path='bert-base-uncased', aug_p=0.25, device='cuda')`

**Comment by mustfkeskin** [comment]
`device='cuda'`
this code works thanks
