### ISSUE TITLE
how can i pass your nlpaug algo for  dataframe

### ISSUE THREAD

**Issue by Somabhadra** [makcedward/nlpaug#209]
Hi,
i am trying to pass nlpaug for my minority class 0 but unable to pass for dataframe.

Example
data=pd.read_csv("new.csv")
from tqdm import tqdm
aug_w2v = naw.WordEmbsAug(
    model_type='glove', model_path='glove.6B.100d.txt',
    action="substitute")
data["text"] is my input and data["label"] is 0 or 1.now i want to use aug_w2v  for my data. Please guide me

**Comment by makcedward** [comment]
Since nlpaug only supports string or list of string only, cannot pass it for pandas dataframe. I will suggest the following code to do so

```
aug_data = []
for label, d in data.groupby('label']):
  a_data = aug_w2v.augment(d)
  a_data = pd.DataFrame(aug_data, columns=['text'])
  a_data['label'] = label
  aug_data.append(a_data)

aug_data = pd.concat(aug_data)
```
