### ISSUE TITLE
Can't use  CUDA on Google Colab

### ISSUE THREAD

**Issue by genetixx01** [makcedward/nlpaug#211]
Hi makcedward,
Thanks for this very usefull library. I'm currently trying to use ContextualWordEmbsAug() (with model_path='bert-base-uncased') on google colab in order to run it on GPU but I get the following error. I'm not an expert, but I don't have any problem running Pytorch on GPU.
Thanks a lot.

RuntimeError Traceback (most recent call last)

in ()
1 #sub_set['aug text'] = sub_set.apply(lambda x: aug.augment(x['text']), axis =1)
2 # df.apply(lambda x: func(x['col1'],x['col2']),axis=1)
----> 3 aug0 = aug.augment(my_text)
4
5 # aug1 = aug.augment(sub_set.iloc[0,2])

11 frames

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
1911 # remove once script supports set_grad_enabled
1912 no_grad_embedding_renorm(weight, input, max_norm, norm_type)
-> 1913 return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
1914
1915

RuntimeError: Input, output and indices must be on the current device

**Comment by genetixx01** [comment]
I want to try CUDA in order to speed up my process because I have about 3000 texts that a would like to "augmente" for data classification with pytorch. Currently, it takes me around one min to create a text with the method : aug = naw.ContextualWordEmbsAug(...). 

If I want to create 3000 augmented texts, it will take me around 50 hours and I don't have this time. I was hoping CUDA could speed up this process. Otherwise, would you have a similar Contextual embedding augmenter that would make a similar job but faster?

Thanks a lot,

**Comment by narayanacharya6** [comment]
@genetixx01 Any resolution or workaround for this issue?

**Comment by narayanacharya6** [comment]
Ok this might sound stupid, but after spending 2 hours on this what worked for me was `Runtime > Factory reset runtime` on Google Colab.

**Comment by genetixx01** [comment]
Hi @narayanacharya6 , 
Nope, I did not have any answer and I finally ended up doing it overnight and it took me 4 days in total... Not very efficient. Are you saying that with the factory reset runtime you were able to use the library on CUDA?

**Comment by narayanacharya6** [comment]
Yes @genetixx01 . Ran augmentation for 12k documents in under 1 hour using CUDA after factory reset runtime.

**Comment by genetixx01** [comment]
That's great! OK, I'm going to try that next time! 
Hope it will work. Thanks for the tips! :-)

**Comment by makcedward** [comment]
it seems that the "device" name is incorrect. [Reference](https://stackoverflow.com/questions/64914598/pytorch-runtimeerror-input-output-and-indices-must-be-on-the-current-device)

May I know what "device" variable do you use?

**Comment by makcedward** [comment]
Btw, I just tested in colab and it works as expected. https://colab.research.google.com/drive/1A152yd4M5Lzo6rjP-gmFSNnklusT_xC0?usp=sharing.

If you do not mind, may you share your colab for further checking?
