### ISSUE TITLE
Always French in backtranslation?

### ISSUE THREAD

**Issue by wilmerhenao** [makcedward/nlpaug#213]
I was checking the files that got downloaded when I was running backtranslation. Instead of German, the downloaded files seem to belong to French? I'm confused.

Also, can you point out how to get them from folder. This line always fails: 

os.environ["MODEL_DIR"]. 

I'm not sure where's the model1.pt file and the directory. Thanks!

**Comment by makcedward** [comment]
BackTransalction model leverage [fairseq ](https://github.com/pytorch/fairseq/blob/1bba712622b8ae4efb3eb793a8a40da386fe11d0/examples/translation/README.md )to perform the operation. I am not familiar with both French and German, so I cannot confirm it but I believe it should be correct as it is released by facebook team.

For "model1.pt ", it refers to the model in fairseq under fairseq repo/ temo folder. It should be downloaded automatically. For testing, you may either try "model1.pt" or "model.pt" which depends on whether more than 1 model exists.

Suppose that, it stored in .cache/torch/hub/pytorch_fairseq_master in your home directory. If you really want to download source model file, you may checkout the URL in [here](https://github.com/pytorch/fairseq/blob/b0ae834d528a4a466202107a22356aed71bb6161/fairseq/models/transformer.py)


Finally, may you share the full exception?
