### ISSUE TITLE
NameError: name 'AutoModelForSeq2SeqLM' is not defined

### ISSUE THREAD

**Issue by vishxl** [makcedward/nlpaug#223]
Getting 'NameError: name 'AutoModelForSeq2SeqLM' is not defined' error on the version `1.1.4`. It is working just fine on `1.1.3` for the Back Translation Aug task. 
Note: it throws the same error even after installing transformers package.
Here's the complete error message: 
```
/usr/local/lib/python3.7/dist-packages/nlpaug/model/lang_models/machine_translation_transformers.py in __init__(self, src_model_name, tgt_model_name, device, silence)
     22         except ModuleNotFoundError:
     23             raise ModuleNotFoundError('Missed transformers library. Install transfomers by `pip install transformers`')
---> 24 
     25         self.src_model_name = src_model_name
     26         self.tgt_model_name = tgt_model_name

NameError: name 'AutoModelForSeq2SeqLM' is not defined
```

**Comment by makcedward** [comment]
what is the transformers library version? It seems like AutoModelForSeq2SeqLM is released after 4.4 version

**Comment by vishxl** [comment]
> what is the transformers library version? It seems like AutoModelForSeq2SeqLM is new after version

The latest version 4.7.0

**Comment by makcedward** [comment]
I tried to simulate your scenario.

I guess it is related to importliob_metadata issue. Starting from transformers 4.5 version, they changed the dependency code checking.[ importlib_metadata.version](https://github.com/huggingface/transformers/blob/master/src/transformers/utils/versions.py#L105) function is used to validate dependency checking. However, numpy library is return None therefore, error is throw and nlpaug catch the error.

Here is the coding for checking None return from importlib_metadata.version function

```
import importlib_metadata
got_ver = importlib_metadata.version(pkg)
print(got_ver)
```

Suggest either use transformers 4.4 or upgrading to python 3.9

May you try to import transformers to see whether you can see the following exception?

```
~/anaconda3/envs/nlpaug_dev/lib/python3.8/site-packages/transformers/utils/versions.py in require_version_core(requirement)
    119     """require_version wrapper which emits a core-specific hint on failure"""
    120     hint = "Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git master"
--> 121     return require_version(requirement, hint)
    122 
    123 

~/anaconda3/envs/nlpaug_dev/lib/python3.8/site-packages/transformers/utils/versions.py in require_version(requirement, hint)
    113         for op, want_ver in wanted.items():
    114             print('pkg:', str(pkg), str(got_ver), str(want_ver))
--> 115             _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
    116 
    117 

~/anaconda3/envs/nlpaug_dev/lib/python3.8/site-packages/transformers/utils/versions.py in _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
     43 def _compare_versions(op, got_ver, want_ver, requirement, pkg, hint):
     44     if got_ver is None:
---> 45         raise ValueError("got_ver is None")
     46     if want_ver is None:
     47         raise ValueError("want_ver is None")

ValueError: got_ver is None
```

**Comment by vishxl** [comment]
Running this code,
```
import importlib_metadata
got_ver = importlib_metadata.version(pkg)
print(got_ver)
```
Returns the following output:
`4.7.0`

Thank you for your help, the following solution worked:

### Solution

- Changing the transformers version to `4.3.3`

- Changing model name in this snippet of code

```
back_translation_aug = naw.BackTranslationAug(
    from_model_name='transformer.wmt19.en-de', 
    to_model_name='transformer.wmt19.de-en'
)
```
from `transformer.wmt19.en-de` and `transformer.wmt19.de-en` to `facebook/wmt19-en-de` and `facebook/wmt19-de-en` [hosted on Huggingface] respectively worked.

#### Links

- [facebook/wmt19-en-de](https://huggingface.co/facebook/wmt19-en-de)
- [facebook/wmt19-de-en](https://huggingface.co/facebook/wmt19-de-en)

**Comment by makcedward** [comment]
In transformers 4.5+ versions, 

when running the following code, the "got_ver" should be None

```
mport importlib_metadata
got_ver = importlib_metadata.version('numpy')
print(got_ver)
```

**Comment by vishxl** [comment]
> In transformers 4.5+ versions,
> 
> when running the following code, the "got_ver" should be None
> 
> ```
> mport importlib_metadata
> got_ver = importlib_metadata.version('numpy')
> print(got_ver)
> ```
On `transformers==4.7.0`, it is returning the respective version number, I have attached the screenshot for reference. 

![image](https://user-images.githubusercontent.com/18505095/122829177-4bcd2e80-d304-11eb-94d8-9f1fc0c19b54.png)
