### ISSUE TITLE
MFCCS augmentations

### ISSUE THREAD

**Issue by Falmi** [makcedward/nlpaug#225]
I only found the sample code for spectrogram argumentation in the package you provide. Based on the example you provide for spectrogram augmentation, I wrote the Loudness augmentation script for MFCCS data as follows. Hence, I was wondering if this technique is correct! 

import nlpaug.augmenter.spectrogram as nas
import librosa
stride=0.01
window_size=0.025
input_path ='audio.wav'
nmfcc=13
pcm, sr = librosa.load(input_path, sr=None)
sample_stride = int(sr * stride)
window = int(sr * window_size)
mfccs = librosa.feature.mfcc(pcm, sr, n_mfcc=nmfcc, n_fft=window, hop_length=sample_stride)
aug = nas.LoudnessAug()
aug_audio = aug.substitute(mfccs)

**Comment by makcedward** [comment]
You are correct.  You may visualize results by using this code

```
from nlpaug.util.audio.visualizer import AudioVisualizer
AudioVisualizer.spectrogram('Original', mfccs)
AudioVisualizer.spectrogram('Augmented', aug_audio)

```
