### ISSUE TITLE
BackTranslationAug fails when fed with a large corpus of texts

### ISSUE THREAD

**Issue by DrMatters** [makcedward/nlpaug#226]
I tried to apply the BackTranslationAug to a corpus 10k documents large (with up to 45 tokens each). The operation failed with "CUDA out of memory. Tried to allocate 5.51 GiB (GPU 0; 15.90 GiB total capacity; 12.36 GiB already allocated; 2.35 GiB free; 12.66 GiB reserved in total by PyTorch)"

Possible solution: add batching to the augmentation operation

**Comment by DrMatters** [comment]
I'm working on adding batching

**Comment by makcedward** [comment]
Batch processing is supported from 1.1.5 release
