### ISSUE TITLE
In nlpaug\model\lang_models\machine_translation_transformers.py, PreTrainedTokenizerBase is given an error

### ISSUE THREAD

**Issue by Amphagory** [makcedward/nlpaug#233]
Version 1.16
import nlpaug.augmenter.word as naw

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
----> 1 import nlpaug.augmenter.word as naw

C:\Anaconda\envs\machine_learning_python_3.8\lib\site-packages\nlpaug\augmenter\word\__init__.py in <module>
      5 from nlpaug.augmenter.word.tfidf import *
      6 from nlpaug.augmenter.word.spelling import *
----> 7 from nlpaug.augmenter.word.context_word_embs import *
      8 from nlpaug.augmenter.word.synonym import *
      9 from nlpaug.augmenter.word.antonym import *

C:\Anaconda\envs\machine_learning_python_3.8\lib\site-packages\nlpaug\augmenter\word\context_word_embs.py in <module>
      8 
      9 from nlpaug.augmenter.word import WordAugmenter
---> 10 import nlpaug.model.lang_models as nml
     11 from nlpaug.util import Action, Doc
     12 

C:\Anaconda\envs\machine_learning_python_3.8\lib\site-packages\nlpaug\model\lang_models\__init__.py in <module>
     10 from nlpaug.model.lang_models.bart import *
     11 from nlpaug.model.lang_models.fill_mask_transformers import *
---> 12 from nlpaug.model.lang_models.machine_translation_transformers import *
     13 from nlpaug.model.lang_models.summarization_transformers import *
     14 from nlpaug.model.lang_models.lambada import *

C:\Anaconda\envs\machine_learning_python_3.8\lib\site-packages\nlpaug\model\lang_models\machine_translation_transformers.py in <module>
     11 
     12 
---> 13 class MtTransformers(LanguageModels):
     14     def __init__(self, src_model_name='facebook/wmt19-en-de', tgt_model_name='facebook/wmt19-de-en',
     15                  device='cuda', silence=True, batch_size=32, max_length=None):

C:\Anaconda\envs\machine_learning_python_3.8\lib\site-packages\nlpaug\model\lang_models\machine_translation_transformers.py in MtTransformers()
     44 
     45     def translate_one_step_batched(
---> 46             self, data, tokenizer: PreTrainedTokenizerBase, model: MarianMTModel
     47     ):
     48         tokenized_texts = tokenizer(data, padding=True, return_tensors='pt')

NameError: name 'PreTrainedTokenizerBase' is not defined

**Comment by makcedward** [comment]
what is the transformers version?

**Comment by makcedward** [comment]
Fixed. Please try 1.1.7 version
