### ISSUE TITLE
No documentation or code for ContextualWordEmbsForSentenceAug

### ISSUE THREAD

**Issue by thehayat** [makcedward/nlpaug#234]
The library is amazing if supports sentence augumentation. But there is no documentation on how to use the ContextualWordEmbsForSentenceAug with GPT or XLNet. Please add it to the documentation.

**Comment by makcedward** [comment]
The process of docs generation is broken due to a library dependency issue. It is fixed now. Please check out the doc from here
https://nlpaug.readthedocs.io/en/latest/augmenter/sentence/context_word_embs_sentence.html
