### ISSUE TITLE
Error of BackTranslationAug() method

### ISSUE THREAD

**Issue by Kelvin-Ho** [makcedward/nlpaug#238]
I'm using BackTranslationAug to create data augmentation. I put a list of text into a loop and get backtranslation one by one. The previous 31 texts can be back-translated successfully but when I come to the 32nd text an error pop-up.
Coud you please point out what's problem ?
![82369708](https://user-images.githubusercontent.com/34711947/127806279-b2e4ec9b-0863-447c-a509-7d3fd49e84be.jpg)
![1194477704](https://user-images.githubusercontent.com/34711947/127806285-f855554c-3135-4fe7-848a-d0238c6b9eb0.jpg)
![111655846](https://user-images.githubusercontent.com/34711947/127806305-800c6572-d2c2-498f-9db6-878c07e4a423.jpg)

**Comment by makcedward** [comment]
Tried to simulate the problem but cannot reproduce it. Is it happen every time in the last batch of data? May you share data if possible?

**Comment by DrMatters** [comment]
> Tried to simulate the problem but cannot reproduce it. Is it happen every time in the last batch of data? May you share data if possible?

He wrote that he uses batch_size=32, but runs augmentations on a single element.

**Comment by makcedward** [comment]
Finally, I was able to reproduce it but I cannot explain. Try to avoid using Helsinki-NLP model. Tried not to use Helsinki-NLP model and it works well. 
![image](https://user-images.githubusercontent.com/36614806/136139057-fd3af271-baf6-4567-99c3-7754b145a096.png)
![image](https://user-images.githubusercontent.com/36614806/136139080-0c6f711f-5a3f-4e82-bd9c-a8d1a86c52b6.png)

**Comment by DrMatters** [comment]
Is this error consistent?

**Comment by makcedward** [comment]
Yes, it is. Once switching to other translation models, the error gone
