### ISSUE TITLE
Caching suggestion for embedding speedup

### ISSUE THREAD

**Issue by Schommer475** [makcedward/nlpaug#240]
A large part of the time cost for running augmentations using word embedding models with substitution is the call to `self.model.predict(word)` which has calls to `np.dot(self.normalized_vectors, source_vector)` and `np.argpartition(-scores, self.top_k+2)[:self.top_k+2]`, both of which are slow.
However, one thing of note is that the `predict(word)` function will always return the same list of options for a given word, regardless of how many times it is called. This means that if the results of the predictions could be saved it could result in a lot of speedup down the line, especially in cases where a given sentence needs to be augmented many times and/or there is a decent amount of overlap between the words in different sentences.
The difficulties in simply storing results are twofold: 

1. It is memory intensive without control on top of the model itself already being memory intensive.
2. It would need to be made safe for use with multi-threading/multiprocessing formats, since adding a cache would now involve a write operation.

Adding an actual caching system to keep the size of what is stored down would solve the memory issues, but would require some sort of interface so that users can control the size of the cache based on their memory needs. It would also do nothing about the issue of needing it to be multi-threading/multiprocessing safe.

As a compromise position, the following changes are suggested:

1. The `Augmenter.augment()` method is updated to allow a list of 2-tuples where the 2-tuples are of the format: (data,n) where data is an individual sentence, etc. to be augmented and n is the number of times to augment that particular piece of data.
2. The augmenter class at the appropriate level is updated to allow the user to turn the caching on or off depending on their memory needs.
3. 'caching', if enabled, will occur on a per-transaction basis (every call to `augment()` is a transaction and values will only be stored within the method call and discarded at the end. 
4. If caching is turned on, all of the pre-processing for every sentence and the selection for augmentation indexes/words for every augmentation occurs before any call to `self.model.predict()` is made and a list of words to substitute as well as how many substitutions to generate for each word is created. In addition, any information needed to be able to efficiently pop the substitutions into place once obtained is stored. 
5. Once the pre-processing is taken care of the list of words is iterated through. For each word in the list: `predict(word)` is called, from the returned list of `top_k` words `n` are selected with replacement where `n` is the total number of substitutions to generate for that word, the generated substitutions are put into the correct locations.
6. The output is created 

This solution would allow for a decent potential speedup to the substitution operation while maintaining safety for multi-threading/multiprocessing operations and providing decent control of memory usage. Additionally, users would be able to control the memory usage by controlling how many sentences they send in at once and/or by turning the caching off.

**Comment by makcedward** [comment]
Will review and consider the implementation. On the other hand, due to the performance of the loading model, the package switched to use gensim for word2vec, fasttest and glove model. See whether performance improved too
