### ISSUE TITLE
Add Custom Dictionary of OCR-Augment

### ISSUE THREAD

**Issue by Olivia-fsm** [makcedward/nlpaug#241]
Hi, nlpaug team! I am using your tool to do a OCR shape-alike data augmentation. Could I specify our own Dict {'o'->0, 'd'->'cl'} when doing the augmentation?

**Comment by makcedward** [comment]
Enhanced to support this scenario. You may download the dev version (pip install git+https://github.com/makcedward/nlpaug.git) for trail.

You may either pass dict or json file path when initializing OCRAug augmenter. The format should be key and a list of possible alternatives. As your example, it should be 
{'o'->0, 'd'->'cl'}

Here is the example of pass dict
```
mapping = {'o': ['0'], 'd': 'cl'}
aug = OcrAug(dict_of_path=mapping)
```

You can also pass json file path as parameter.
`aug = OcrAug(dict_of_path='sample.json')`

**Comment by makcedward** [comment]
Supported in 1.1.8 version
