### ISSUE TITLE
Other language support

### ISSUE THREAD

**Issue by seungyoon-woo** [makcedward/nlpaug#244]
Hi nlpaug team.
I'm wondering if your team considering support other language of OcrAug (ex. korean)
Or is there other any I can use in custom way?

**Comment by makcedward** [comment]
Hi, Please free feel to contribute to it. OcrAug is designed to load a pre-defined JSON file or python dictionary object. You may have a look at the [English version JSON file](https://github.com/makcedward/nlpaug/blob/master/nlpaug/res/char/ocr/en.json) as reference or example of [python object](https://github.com/makcedward/nlpaug/issues/241). Here is the structure
```
{
  source_character: ["list of alternative character"],
  source_character2: ["list of alternative character"]
}
```

You can either pass python object/ JSON file path to OcrAug
```
aug = nac.OcrAug(dict_of_path=mapping)
aug = nac.OcrAug(dict_of_path='./your_json_file.json')
```

nlpaug supports this feature from 1.1.8 (released on Oct 18, 2021)

**Comment by makcedward** [comment]
Supported in 1.1.8 version
