### ISSUE TITLE
gpu not being fully used  in ContextualWordEmbsAug

### ISSUE THREAD

**Issue by Jiaxin-Wen** [makcedward/nlpaug#246]
Hello

I'm using bert model for `ContextualWordEmbsAug`. 

I've tried to assign different value to batch_size, like 128 or 1024, but the gpu memory usage is unchanged(1035MB). And the runtime is too slow.

Also, I've seen the warning below from transformers.

```bash
transformers/pipelines/base.py:899: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
```

**Comment by makcedward** [comment]
#248. Switched to native API rather than using pipeline API.

**Comment by hionwi** [comment]
@makcedward 
Can you tell me how to switch to native api

**Comment by makcedward** [comment]
install the latest version (1.1.9). It will use native API by default
