### ISSUE TITLE
stopwords and tokenizer

### ISSUE THREAD

**Issue by jadermcs** [makcedward/nlpaug#247]
When a list of stopwords is provided, like:
```python
aug = naw.ContextualWordEmbsAug(model_path='bert-base-uncased',
                                action="substitute", stopwords=["[id]", "[year]"])
```

The stopwords is filtered after the tokenization, so it will not match the specified stopword
```python
aug.augment("My id is [id], and I born in [year]")
>> "my key is [ age ], i've born another [ year ]"
```
How can I solve this?

**Comment by makcedward** [comment]
Since the tokenization step is processed before checking stopwords, "My id is [id]" is tokenziend as "My", "id", "is", "[", "id", "]". 

I am working this bug fix.

**Comment by makcedward** [comment]
Pushed the latest change to handle this scenario. See whether it handle your scenario by install dev version

`pip install git+https://github.com/makcedward/nlpaug.git`
