### ISSUE TITLE
WordEmbeddings Random Insertion selects random word from entire vocab rather than from top-k closest words

### ISSUE THREAD

**Issue by ARDivekar** [makcedward/nlpaug#250]
This is the line: https://github.com/makcedward/nlpaug/blob/master/nlpaug/augmenter/word/word_embs.py#L125 

I think it should be `self.model.predict()`, but I am not sure.

**Comment by makcedward** [comment]
Yes. it should be top-k.

**Comment by makcedward** [comment]
After reviewing the whole process, it can be only drawn words from the entire corpus. Although we can leverage CBOW to predict the target word (i.e. newly inserted word), we are lack of trained neural networks output layer from those pre-trained models. Therefore, we cannot use this approach. [Here](https://github.com/RaRe-Technologies/gensim/blob/6e362663f23967f3c1931e2cb18d3d25f92aabb5/gensim/models/word2vec.py#L1799) is the flow of detail implementation in gensim
