### ISSUE TITLE
`augment_batch` for BertAug, or a GPU option

### ISSUE THREAD

**Issue by shuntaroy** [makcedward/nlpaug#26]
Thank you for your development.
I have used BertAug for my preliminary experiments.
Since BERT on CPU is awfully slow, it would be great if BertAug had a method to augment examples in a batch so that GPUs can be used.
Just a suggestion for a sort of production-level use.
Thanks!

**Comment by makcedward** [comment]
Thank you for your comment. Will evaluate GPU option

**Comment by makcedward** [comment]
You can switch to use the following code to use GPU option

```
aug = nas.ContextualWordEmbsAug(model_path='bert-base-uncased', device='cuda')
augmented_text = aug.augment(text)
```
