### ISSUE TITLE
Minimum python version support and possibility to relax pandas requirement

### ISSUE THREAD

**Issue by chiragjn** [makcedward/nlpaug#278]
I wanted to know what is the official minimum supported python version for this package. I understand Python 3.6 has reached EOL but the only strong requirement that stops nlpaug 1.1.8 and above from working on python 3.6 is `pandas>=1.2.0` because pandas 1.2.0 dropped support for Python 3.6

So it would be great if this package can add the minimum supported Python version in `setup.py`
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires

and if there is a plan to support Python 3.6 and if pandas can safely be relaxed to a lower version (e.g. `pandas>=1.0.0`) then it should be relaxed - then the latest nlpaug would be useable on Python 3.6 too :smile:

**Comment by makcedward** [comment]
Thank you very much. Will add python_requires for python 3.7+
