### ISSUE TITLE
time_dim and freq_dim in vtlp

### ISSUE THREAD

**Issue by 980202006** [makcedward/nlpaug#280]
I noticed that in the implementation of vtlp, the following code was used, but I observed the return description of librosa.core.stft. The first one should be the frequency dimension, and the second one should be the frame dimension. Is there any naming error?
![image](https://user-images.githubusercontent.com/24452502/160087503-2a4eaa70-73c7-4b60-86f4-c9a6b555a6b0.png)

![image](https://user-images.githubusercontent.com/24452502/160087407-5e0d0511-e53b-45ef-b780-6896d12a195e.png)

**Comment by makcedward** [comment]
You are right. It should be freq_dim, time_dim = stft.shape. Applied fix
