### ISSUE TITLE
Add link to documentation for supported synonyms for nlpaug.augmenter.word.synonym

### ISSUE THREAD

**Issue by ArtificialTruth** [makcedward/nlpaug#289]
[Current docstring says:](https://nlpaug.readthedocs.io/en/latest/augmenter/word/synonym.html) 
   `:param str lang: Language of your text. Default value is 'eng'.`

A list of all supported languages would be helpful. I believe it is this list?
http://compling.hss.ntu.edu.sg/omw/

**Comment by makcedward** [comment]
Good suggestion. reference link will be added in the coming release.

**Comment by LeyiJiang** [comment]
This website can't be opened now, so what should I do if I want to use another language?
