### ISSUE TITLE
I guess this is a bug...

### ISSUE THREAD

**Issue by beyondguo** [makcedward/nlpaug#295]
https://github.com/makcedward/nlpaug/blob/f34e7cd3e6e6b2c714127b9613a27d991b73106e/nlpaug/model/lang_models/lambada.py#L58

Orig:
```python
input_text = 'label_{} {}'.format(label, self.sep_token)
```

I believe it should be:
```python
input_text = '{} {}'.format(label, self.sep_token)
```

Because the original input format mismatches the format in the pre-processing script:
```python
def prepare_mlm_data(labels, texts, output_file_path, sep_token):
	if not os.path.exists(output_file_path):
		os.makedirs(output_file_path)
	with open(os.path.join(output_file_path, 'mlm_data.txt'), 'w') as f:
		for label, text in zip(labels, texts):
			f.write(' '.join([str(label), sep_token, text]) + '\n')
```

I have tried to generate samples by your code, but the generated text is very strange. After I made the changes above, the results become normal.

**Comment by makcedward** [comment]
You are right. This fix will be included in the coming release
