### ISSUE TITLE
Don't change specified words.

### ISSUE THREAD

**Issue by xxupiano** [makcedward/nlpaug#296]
If I'd like not to change some specified words in one text when conducting data augmentation, could I achieve this with 'nlpaug'?
For example, 'nlpaug' augmented the text 'The quick brown fox jumps over the lazy dog.' into 'The quick 40Mbtye fox jumps _particular_ the lazy L6Y1XGT.', in which words 'fox' and 'dog' still remained as I hope.
Thanks a lot.

**Comment by makcedward** [comment]
Hi, you can use `stopwords` parameter. Here is sample code

```
import nlpaug.augmenter.word as naw

aug = naw.RandomWordAug(action="substitute", stopwords=['fox', 'dog'])

text = ['The quick brown fox jumps over the lazy dog']
import nlpaug.augmenter.word as naw

aug = naw.RandomWordAug(action="substitute", stopwords=['fox', 'dog'])

text = ['The quick brown fox jumps over the lazy dog']

for _ in range(100):
    aug_data = aug.augment(text)
    aug_text = aug_data[0]
    if 'fox' not in aug_text and 'dog' not in aug_text:
        print(aug_text)
        raise
else:
    print('No found')
for _ in range(100):
    aug_data = aug.augment(text)
    aug_text = aug_data[0]
    if 'fox' not in aug_text and 'dog' not in aug_text:
        print(aug_text)
        raise
else:
    print('No found')
```

**Comment by xxupiano** [comment]
Thanks for your reply. Can one stopword contain more than one word? I tried it but failed.

**Comment by makcedward** [comment]
Input type is a list so it supports more than 1 word. Be careful of the case (case sensitive). If still dun work, may you share sample data?

**Comment by xxupiano** [comment]
I understand how to use the 'stopwords' parameter finally. Thank you very much!
