### ISSUE TITLE
Reducing the number of replaced characters

### ISSUE THREAD

**Issue by ricardopieper** [makcedward/nlpaug#3]
Hi Edward, thank you for this great work.

I'm trying to use the QwertyAug augmenter, but I'm having some issues controlling the number of replaced characters.

For instance: 
```
aug = naf.Sequential([
    nac.QwertyAug()
])

aug.augment("qual o motivo do meu cartao ainda estar bloqueado?")
```

This results in waaay too many characters being replaced:

```
 wual 9 motibo di m3u carfao aindx esta# bloquezso?
```

I saw that there are some parameters that affect the amount of characters. For instance, if I pass `aug_p = 0.00000000000000001` still way too many characters get replaced. Now I show a test with the sentence "why is my credit card still blocked?":

```
'wh5 id hy crevit carw stilp blpcked?'
```
There's barely any meaning in this sentence anymore. 

The aug_p seems to be the correct parameter. If I pass 1, then all characters change.

Is there a way to further reduce the chance that a given character gets replaced? Ideally, in a sentence with that size, I'd like to replace like 2 or 3 characters.

**Comment by makcedward** [comment]
In coming release, "aug_word_p" and "aug_char_p" parameters will be introduced to Character Augmenter (OcrAug, QwertyAug, RandomCharAug). It controls the percentage of word (or character) for augmentation.

Example
`aug = RandomCharAug(aug_word_p=0.3, aug_char=0.3)`
