### ISSUE TITLE
In the documentation it is unclear about the spelling dictionary

### ISSUE THREAD

**Issue by xihajun** [makcedward/nlpaug#311]
https://nlpaug.readthedocs.io/en/latest/augmenter/word/spelling.html

Here is the code:
https://github.com/makcedward/nlpaug/blob/7618bd9ed58ef9ab9d5f47b69dd0e6bbabeadd70/nlpaug/model/word_dict/spelling.py#L21-L43

So I guess it should be 
```
correct coect correc
word wod wrd
is i iss iss
the th te
first frst
one onee
```

**Comment by xihajun** [comment]
It works:
let's save the correction list as `dic.txt`
```
correct coect correc
word wod wrd
is i iss iss
the th te
first frst
one onee
```
Then we just need to run
```
import nlpaug.augmenter.word as naw
aug = naw.SpellingAug(dict_path='dic.txt')
aug.augment(["correct is the first one"])
>>> ['correc is th first one']
```

**Comment by jhpiedrahitao** [comment]
but you can't have more than one instance of the SpelligAug in order to have more than one spelling dictionary, because all the instances will share the same model -> same dictionary
