### ISSUE TITLE
import nlpaug.augmenter.word

### ISSUE THREAD

**Issue by jxy-001** [makcedward/nlpaug#33]
pytorch_pretrained_bert has been updated to pytorch_transformers，could you please change the code?

**Comment by makcedward** [comment]
Will include this enhancement in next release

**Comment by keherri** [comment]
No sure if this is the same issue, but when I run ```import nlpaug.augmenter.word as naw``` I receive the error ```AttributeError: module 'nlpaug.util' has no attribute 'math'```

I've installed using ```pip install nlpaug```

**Comment by makcedward** [comment]
> No sure if this is the same issue, but when I run `import nlpaug.augmenter.word as naw` I receive the error `AttributeError: module 'nlpaug.util' has no attribute 'math'`
> 
> I've installed using `pip install nlpaug`

It is another issue due to missing declaration. Will fix soon
