### ISSUE TITLE
Are there any options for manipulating the ratio of [delete/insert/substitute/swap]?

### ISSUE THREAD

**Issue by hyeseonko** [makcedward/nlpaug#37]
Hi,
Thank you for releasing your data augmentation code.

I could easily find how to use your code like below.
>> aug = nac.KeyboardAug()
>> augmented_text = aug.augment(text)

However, I wonder if there's any options for manpulating how much I want to denoise the original texts.

Best regards,
Hyeseon

**Comment by makcedward** [comment]
Hi Hyeseon,

Yes, there are several parameter for it. You can refer to https://nlpaug.readthedocs.io/en/latest/augmenter/char/keyboard.html

**Comment by hyeseonko** [comment]
Thank you for your fast reply!

One more thing! 
Could you list up the library requirements on README file? 
I think it would be better and easier for us to use your library !!

**Comment by makcedward** [comment]
Will add it. Thank you for your suggestion

**Comment by makcedward** [comment]
Add libraries installation script in README.md
