### ISSUE TITLE
No 'tfidfaug_w2idf.txt' file

### ISSUE THREAD

**Issue by waterflyer** [makcedward/nlpaug#43]
Under the model folder, there is no 'tfidfaug_w2idf.txt' file which needed for TfIdfAug, please upload it, thank you.

**Comment by makcedward** [comment]
TfIdfAug have to been trained based on your data. You can refer to this [notebook](https://github.com/makcedward/nlpaug/blob/master/example/tfidf-train_model.ipynb) for step of training.

**Comment by waterflyer** [comment]
Oh, I got it, thanks, Edward.
