### ISSUE TITLE
NameError: name 'BertTokenizer' is not defined

### ISSUE THREAD

**Issue by ghost** [makcedward/nlpaug#44]
I got this error: **NameError: name 'BertTokenizer' is not defined**
when I am running the following code: 
`aug = naw.ContextualWordEmbsAug(model_path='bert-base-uncased', action="insert")
augmented_text = aug.augment(text)
print("Original:")
print(text)
print("Augmented Text:")
print(augmented_text)`
______________________________
Returns:

/usr/local/lib/python3.6/dist-packages/nlpaug/model/lang_models/bert.py in __init__(self, model_path, top_k, top_p, device)
     75         self.model_path = model_path
     76 
---> 77         self.tokenizer = BertTokenizer.from_pretrained(model_path)
     78         self.model = BertForMaskedLM.from_pretrained(model_path)
     79 

NameError: name 'BertTokenizer' is not defined

**Comment by askwenhan** [comment]
@hamadazahera There is a try except block in the import header. Have you installed the pytorch-transformers package?

**Comment by makcedward** [comment]
Since not all augmenters (e.g. Audios' augmenter use librosa library, ContextWordEmbAug use pytorch_transformer library) will be used, some library dependencies need to be installed separately.

You may install the following library and try again
`pip install torch>=1.1.0 pytorch_pretrained_bert>=1.1.0`

**Comment by rcalsaverini** [comment]
I had this problem and after installing the `pytorch-transformers` package it was solved. Maybe this should be listed as prerreq in the docs?

**Comment by hqsiswiliam** [comment]
Hi there, I am of the opinion to add those package to the requirement of this package. I solved this problem by `pip install transformers` and I found the author just ignore the import error so it is hard to find the exact problem intuitively:
I think it is better to add some **user warning** if you don't want to raise the exception.
```python
try:
    import torch
    from transformers import BertTokenizer, BertForMaskedLM
    # from transformers import AutoModel, AutoTokenizer
except ImportError:
    # No installation required if not using this function
    pass
```

**Comment by makcedward** [comment]
> Hi there, I am of the opinion to add those package to the requirement of this package. I solved this problem by `pip install transformers` and I found the author just ignore the import error so it is hard to find the exact problem intuitively:
> I think it is better to add some **user warning** if you don't want to raise the exception.
> 
> ```python
> try:
>     import torch
>     from transformers import BertTokenizer, BertForMaskedLM
>     # from transformers import AutoModel, AutoTokenizer
> except ImportError:
>     # No installation required if not using this function
>     pass
> ```

In case, user uses ContextualWordEmbsAug without installing torch and transformer. An [exception ](https://github.com/makcedward/nlpaug/blob/master/nlpaug/model/lang_models/language_models.py#L19)will be raised. 

Try to prevent any unexpected warning message when user do not use it.
