### ISSUE TITLE
Short token problems / what happened to min_char?

### ISSUE THREAD

**Issue by afriedman412** [makcedward/nlpaug#52]
Hey Edward --
Is there a reason you took out the min_char parameter from the RandomChar augmenter? At the moment it seems like it ignores augmentations made to short words and just returns the original text.

For example, if the augmenter would make "hi there" into "hW there" it just returns "hi there" instead. Seems like "min_char" is permanently set at 3.

Thanks!

**Comment by makcedward** [comment]
You are right. min_char is designed to ignore short words. However, I did not remove min_char from RandomChar augmenter. May you share your test case?

RandomAug's interface
https://github.com/makcedward/nlpaug/blob/master/nlpaug/augmenter/char/random.py#L42
Actual operation
https://github.com/makcedward/nlpaug/blob/master/nlpaug/augmenter/char/char_augmenter.py#L59
