### ISSUE TITLE
UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by luli245683** [makcedward/nlpaug#56]
Hello, when I use sentence augmentation, I got the following problem...

![image](https://user-images.githubusercontent.com/43977140/68024199-5af10a00-fce4-11e9-804b-bb6527505c9c.png)

I just want to download gpt2 pre-trained model and try to augment the sentence.
---
nas.ContextualWordEmbsForSentenceAug(model_path='gpt2')

**Comment by makcedward** [comment]
@luli245683 
Can you share more exception stack for troubleshoot. Also, may you share your environment configuration such as OS, python kernel

**Comment by luli245683** [comment]
@makcedward 
hi, thank you for your response.
I solved this problem, the reason is I did not install the nltk package.
Sorry for wast your time.
