### ISSUE TITLE
Producing deterministic results

### ISSUE THREAD

**Issue by ricardopieper** [makcedward/nlpaug#6]
I think the library should have means to produce the same results given the same inputs. However, I've observed that each time I run any augmenter, the results vary. 

This is expected, but sometimes it might be interesting to be a bit more deterministic. I've done it using this piece of code:

```
import numpy as np
np.random.seed(1000)
import random
random.seed(1000)
```

This is less than ideal since it changes the seed globally. I wonder if there is a way to implement this properly.

**Comment by makcedward** [comment]
@ricardopieper 
Random behavior is designed on purpose to produce more synaptic data. 

You may update seed before invoking augmenter. Also, you can set "aug_n" parameter to 1 when using BertAug, FasttextAug, GloVeAug and Word2vecAug. It will always get the highest similarity word.

**Comment by ricardopieper** [comment]
Seems fair.

About aug_n: In my understanding (actually it's just a guess), aug_n means that the algorithm will choose one between `aug_n` most similar words, is that correct?

Is it possible that it could choose the very same word if I set it to 1? I've done some tests and that seemed to be the case for my particular fasttext model. It's a very dirty model. I will try doing this test tomorrow. 

I mention it because replacing by the same word doesn't seem useful in my naive understanding, but again I don't clearly remember if this happens at all.

**Comment by makcedward** [comment]
@ricardopieper 
You may refer to 
https://github.com/makcedward/nlpaug/blob/a49eb0782d92c61f8dd9a8c324ed51e2e15f3e49/nlpaug/augmenter/word/word_embs_aug.py#L62

and 
https://github.com/makcedward/nlpaug/blob/a49eb0782d92c61f8dd9a8c324ed51e2e15f3e49/nlpaug/model/word_embs/word_embeddings.py#L51

Suppose that it will get the top n +1 (if aug_n is 1, then it will get top 2) similar word and it will filter out same word in next line. So, it should not returning same word. Notice that "Apple" is different from "apple". 

If you do see the same word is returned, can you share your test case for debug?

**Comment by ricardopieper** [comment]
I'll open a proper issue if I see this happening.
