### ISSUE TITLE
Suggestion for GPT2 decoding speedup

### ISSUE THREAD

**Issue by chiragjn** [makcedward/nlpaug#61]
According to transformers documentation, GPT2 LM head supports an argument called `past` that speeds up decoding by reusing computed attention tensors from previous steps. I have started changes in my fork to be able to get some numbers

https://github.com/chiragjn/nlpaug/pull/2/

I am not entirely sure how to get this working for XLNET, but there is a similar, `mems` argument

Would you accept such PR upstream if it speeds up decoding?

**Comment by makcedward** [comment]
@chiragjn 
It will be good if you can submit PR as I am working on improving performance in terms of speed.

**Comment by chiragjn** [comment]
Closing this as #63 is in master
