### ISSUE TITLE
is there a way to adopt this  package to french language ?

### ISSUE THREAD

**Issue by Asma-droid** [makcedward/nlpaug#69]

**Comment by Asma-droid** [comment]
I would like to use the nlpaug for a french context. 
I have loaded the french model "frWac_non_lem_no_postag_no_phrase_200_cbow_cut0.bin" and i have tried to substitute words using word2vec but the generated sentences have no sense. 

below a simple example:

Original:
Bonjour, J'aimerais une attestation de l'employeur certifiant que je suis en CDI.
Augmented Text:
b"Bonjour, J'aimerais une attestation Une l'employeur certifiant que ne_pas un_bon en CDI."
b"Bonjour, J'aimerais une UETA toute l'employeur certifiant que je aqu\xe2\x94\x9c\xc2\xa1 en CDI."
b"Bonjour, J'aimerais une attestation \xe2\x94\x9c\xc2\xactre l'employeur certifiant que zo suis voor_de CDI."
b"Bonjour, J'aimerais qu'un attestation de l'employeur certifiant lo_que er_een suis en CDI."
b"Bonjour, J'aimerais de_faire attestation dit l'employeur certifiant que je suis ser\xe2\x94\x9c\xc3\xad CDI."
b"Bonjour, J'aimerais \xe2\x94\x9c\xc3\xa1_l' attestation de l'employeur certifiant qui je suis \xe2\x94\x9c\xe2\x8c\x90galement CDI."
b"Bonjour, J'aimerais une attestation Union_Europ\xe2\x94\x9c\xe2\x8c\x90enne l'employeur certifiant que c'est_un por_lo en CDI."

Any help please!

**Comment by makcedward** [comment]
Can you share where I can download the model file?

**Comment by Asma-droid** [comment]
here is the link to the model https://fauconnier.github.io/

**Comment by Asma-droid** [comment]
Hello @makcedward,

The link https://github.com/makcedward/nlpaug/blob/master/example/textual_language_augmenter.ipynb
does not work

**Comment by makcedward** [comment]
uploaded. It seems that word embeddings (e.g. word2vec) cannot handle French while you may try the multi-lingual version of BERT. Welcome to provide feedback
