### ISSUE TITLE
WordNetAug seems to only work for english

### ISSUE THREAD

**Issue by ricardopieper** [makcedward/nlpaug#7]
A simple change to the code may fix this:

    synets.extend(self.model.synsets(pos[i][0], pos=word_pos, lang='por'))
    And:
    for candidate in synet.lemma_names(lang='por'):

In this code, I changed it to generate examples in portuguese. Otherwise it generates random examples in english.

**Comment by makcedward** [comment]
@ricardopieper 
In coming release, "lang" parameter will be added to WordNetAug.
Example
`aug = WordNetAug(lang='por')`
