### ISSUE TITLE
NameError while using ContextualWordEmbsAug

### ISSUE THREAD

**Issue by Alea4jacta6est** [makcedward/nlpaug#71]
I just successfully installed dependencies for ContextualWordEmbsAug and tried one of your examples.

`pip install torch>=1.2.0 transformers>=2.0.0 `

Here is your code that i used:
```

aug = naw.ContextualWordEmbsAug(
model_path='bert-base-uncased', action="substitute")
augmented_text = aug.augment(text)
print("Original:")
print(text)
print("Augmented Text:")
print(augmented_text)
```
The error:
`
NameError: name 'BertTokenizer' is not defined
`
Do you have any idea why it happens?

**Comment by Alea4jacta6est** [comment]
I also tried this script to check that the problem is not in the wrong package installation:
```
import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM

# OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
import logging
logging.basicConfig(level=logging.INFO)

# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
```
it works nice

**Comment by makcedward** [comment]
What is the version of transformers? At least 2.1.x version is expected

**Comment by Alea4jacta6est** [comment]
transformers==2.2.1, i already resolved

**Comment by TongLi3701** [comment]
Hi, I just have the same problem,  I tried 
! pip install torch>=1.2.0 transformers>=2.5.0
! pip install torch>=1.1.0 pytorch_pretrained_bert>=1.1.0
on colab, but still not work , could you please tell me how did you fix it

**Comment by moep0** [comment]
> Hi, I just have the same problem, I tried
> ! pip install torch>=1.2.0 transformers>=2.5.0
> ! pip install torch>=1.1.0 pytorch_pretrained_bert>=1.1.0
> on colab, but still not work , could you please tell me how did you fix it

i have met the same problem, have you solved this?

**Comment by makcedward** [comment]
> Hi, I just have the same problem, I tried
> ! pip install torch>=1.2.0 transformers>=2.5.0
> ! pip install torch>=1.1.0 pytorch_pretrained_bert>=1.1.0
> on colab, but still not work , could you please tell me how did you fix it



> > Hi, I just have the same problem, I tried
> > ! pip install torch>=1.2.0 transformers>=2.5.0
> > ! pip install torch>=1.1.0 pytorch_pretrained_bert>=1.1.0
> > on colab, but still not work , could you please tell me how did you fix it
> 
> i have met the same problem, have you solved this?

What is the error?

**Comment by KiranJ2000** [comment]
Hello, I have encountered the same error 'name BertTokenizer is not defined' even though I have transformers version 3.0.2 installed. Do help!

**Comment by makcedward** [comment]
> Hello, I have encountered the same error 'name BertTokenizer is not defined' even though I have transformers version 3.0.2 installed. Do help!

What is version of nlpaug?
