### ISSUE TITLE
NameError: name 'model_dir' is not defined

### ISSUE THREAD

**Issue by ankurgulati** [makcedward/nlpaug#73]
Trying to run the below code:

```
# model_type: word2vec, glove or fasttext
aug = naw.WordEmbsAug(
    model_type='word2vec', model_path=model_dir + 'GoogleNews-vectors-negative300.bin',
    action="insert")
```

It is giving up the below error:

> NameError: name 'model_dir' is not defined

And I did mention the below code at the top:

```
import os
os.environ["MODEL_DIR"] = '../model'
```

I also tried replacing MODEL_DIR instead of model_dir.

Reference: https://github.com/makcedward/nlpaug/blob/master/example/textual_augmenter.ipynb

**Comment by makcedward** [comment]
You have to download word2vec before using it. You can place anywhere and passing the path to model. 

For example, you can persisit to /data/model/ (for Linux) or D:/model (for window), you just need to pass "/data/model/GoogleNews-vectors-negative300.bin" or "D:/model/oogleNews-vectors-negative300.bin" to "WordEmbsAug". 

Link for download Google's word2vec: https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit
