### ISSUE TITLE
Avoid the text augmentation of a part of a sentence

### ISSUE THREAD

**Issue by Asma-droid** [makcedward/nlpaug#81]
Hello,

I would like to ask you if it is possible to avoid the text augmentation of a pattern in a sentence.

Example:
Original sentence is : I would like to test @[the code] 

How can i avoid the text augmentation of the pattern @[the code]  ???

**Comment by makcedward** [comment]
Do you mean supporting regular expression? 
For example, you want to skip word if the prefix is @[ and the suffix is ]. So the regex is ' @\[[a-zA-Z ]*]\] '

**Comment by Asma-droid** [comment]
Exactly! It is possible to do that with the pg as it is written now or i have to personalize the code ?

**Comment by makcedward** [comment]
It does not support now. Will add it into enhancement list
