### ISSUE TITLE
Problem when reading the ppdb file

### ISSUE THREAD

**Issue by Asma-droid** [makcedward/nlpaug#83]
Hi,

I try to use the ppdb data downloded from the site http://paraphrasing.org/~fujita/resources/lexpanded-PPDB.html.

As the data is very large, i have obtained the error

 File "........\site-packages\nlpaug-0.0.11-py3.7.egg\nlpaug\model\word_dict\ppdb.py", line 49, in read IndexError: list index out of range.

Any help please

**Comment by makcedward** [comment]
which model (language and package) do you use?

**Comment by Asma-droid** [comment]
I have used the Small Package for the french lanuage.

I think that the actual nlp code considers that:
- The word separator is ||| 
- We should have at leat 6 synonyms for a given word

Consequently, it can not be adapted to the existing ppdb packages

**Comment by makcedward** [comment]
It is an official PPDB language pack format. You may download it from http://paraphrase.org/#/download. 

It seems that this [website](http://paraphrasing.org/~fujita/resources/lexpanded-PPDB.html)  use PPDB data source only while using different data format.

**Comment by Asma-droid** [comment]
Thanks for this response :-)

**Comment by lucaskulla** [comment]
Hi @makcedward i have a similar issue. Unfortunately the website:  http://paraphrase.org/#/download is not working anymore (403). I tried the other website you mentioned: https://paraphrasing.org/~fujita/resources/lexpanded-PPDB.html
I downloaded the files there, but I get the error: 
`'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

do you know the reason for that? 

Best, 

Lucas
